#!/bin/bash
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 1
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 2
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 3
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 4
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 5
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 6
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 7
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 8
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 9
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 10
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 11
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 12
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 13
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 14
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 15
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 16
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 17
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 18
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 19
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 20
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 21
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 22
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 23
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 24
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 25
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 26
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 27
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 28
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 29
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 30
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 31
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 32
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 33
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 34
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 35
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 36
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 37
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 38
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 39
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 40
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 41
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 42
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 43
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 44
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 45
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 46
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 47
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 48
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 49
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 50
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 51
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 52
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 53
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 54
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 55
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 56
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 57
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 58
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 59
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 60
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 61
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 62
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 63
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 64
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 65
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 66
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 67
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 68
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 69
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 70
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 71
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 72
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 73
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 74
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 75
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 76
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 77
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 78
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 79
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 80
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 81
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 82
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 83
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 84
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 85
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 86
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 87
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 88
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 89
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 90
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 91
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 92
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 93
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 94
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 95
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 96
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 97
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 98
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 99
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 100
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 101
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 102
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 103
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 104
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 105
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 106
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 107
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 108
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 109
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 110
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 111
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 112
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 113
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 114
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 115
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 116
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 117
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 118
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 119
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 120
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 121
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 122
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 123
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 124
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 125
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 126
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 127
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 128
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 129
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 130
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 131
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 132
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 133
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 134
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 135
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 136
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 137
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 138
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 139
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 140
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 141
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 142
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 143
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 144
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 145
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 146
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 147
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 148
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 149
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 150
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 151
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 152
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 153
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 154
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 155
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 156
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 157
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 158
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 159
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 160
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 161
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 162
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 163
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 164
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 165
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 166
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 167
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 168
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 169
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 170
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 171
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 172
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 173
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 174
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 175
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 176
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 177
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 178
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 179
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 180
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 181
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 182
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 183
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 184
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 185
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 186
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 187
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 188
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 189
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 190
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 191
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 192
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 193
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 194
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 195
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 196
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 197
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 198
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 199
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar 200

