java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
java -jar out/artifacts/Homeostatic_Epidermis_jar/Homeostatic_Epidermis.jar
